os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

language: node_js
node_js:
  - '4.2.1'

before_install:
  - "sudo apt-get update;sudo apt-get install curl libssl-dev build-essential g++ libkrb5-dev"

services:
  - mongodb

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - npm install

env:
  - DB=test TEST_SMTP_USERNAME=ci.surelia@gmail.com TEST_SMTP_PASSWORD=sandimantong
